import streamlit as st

def init_session_state_variables():
    """
    Initializes the session state variables used in the chatbot application which enables data persistence across user interactions and page refreshes within a session.

    This function initializes the following state variables:
    - uploaded_files: A list to store the uploaded files.
    - chat_history: A list to store the chat history.
    - previous_questions: A list to store the questions already asked in the chat.
    - collection_name: The name of the collection being used.
    - current_question: The current question being asked.
    - generated_answer: The answer generated by the AI model.
    - retriever: The retriever model used for question answering.
    - filename: The name of the uploaded file.
    - file_in_upload_form: A boolean flag to indicate if a file is in the upload form. Is used to disable certain buttons when a file is being uploaded.

    If any of these variables are not present in the session state, they are initialized with their default values.
    """
    variables = {
        "uploaded_files": [],
        "chat_history": [],
        "previous_questions": [],
        "collection_name": None,
        "current_question": None,
        "generated_answer": None,
        "retriever": None,
        "filename": None,
        "file_in_upload_form": False
    }

    for variable, default_value in variables.items():
        if variable not in st.session_state:
            st.session_state[variable] = default_value